In [1]:
# numpy- it is a package/library for scientific computing-statistics,maths

import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.random.random((3,4))

array([[0.09295958, 0.28335734, 0.71054728, 0.42410879],
       [0.03517964, 0.06211709, 0.53754194, 0.42963637],
       [0.55989503, 0.95718136, 0.08372311, 0.09793201]])

In [12]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a2.ndim

2

In [16]:
a2.shape

(3, 4)

In [17]:
a3.size

8

In [18]:
a1.itemsize

4

In [19]:
a1.dtype

dtype('int32')

In [20]:
a1.astype(np.int32)
a1.dtype

dtype('int32')

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [23]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [25]:
np.min(a1,axis=1)

array([0, 4, 8])

In [26]:
np.max(a2)

23

In [27]:
np.sum(a1)

66

In [28]:
np.prod(a2)

816826368

In [29]:
np.mean(a1,axis=0)

array([4., 5., 6., 7.])

In [30]:
np.prod(a1,axis=0)

array([  0,  45, 120, 231])

In [31]:
np.var(a1,axis=1)

array([1.25, 1.25, 1.25])

In [32]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [33]:
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)

np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [34]:
np.round(np.random.random((2,3))*100)

array([[38., 24., 30.],
       [50., 19., 31.]])

In [35]:
np.floor(np.random.random((2,3))*100)

array([[28., 75., 52.],
       [88., 30.,  0.]])

In [36]:
np.ceil(np.random.random((2,3))*100)

array([[30., 89., 48.],
       [74., 70., 36.]])

In [37]:
a1 = np.arange(12)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a1[-1]

11

In [39]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a2[1,2]

6

In [41]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
a3[1,0,1]

10

In [43]:
a3[0,0,0]

0

In [44]:
a3[1,1,0]

12

In [45]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
a1[2:5]

array([2, 3, 4])

In [47]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2[0,:]

array([0, 1, 2, 3])

In [49]:
a2[:,2]

array([ 2,  6, 10])

In [50]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [51]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [52]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [53]:
a2[1:2,::3]

array([[4, 7]])

In [54]:
a2[0:2,1::1]

array([[1, 2, 3],
       [5, 6, 7]])

In [55]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [56]:
a3[0,1,:]

array([3, 4, 5])

In [57]:
a3[1,:,1]

array([10, 13, 16])

In [58]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [59]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [60]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [61]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [62]:
a3

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [63]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [64]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [66]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [67]:
#2d to 1d ravel()
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
a5 = np.arange(12).reshape(3,4)
a6 = np.arange(12,24).reshape(3,4)

In [69]:
#stacking - horizontallly , vertically
n = np.hstack((a5,a6))
n

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [70]:
x = np.vstack((a5,a6))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
#splitting - opposite of stacking

np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [72]:
np.vsplit(x,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]