In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
a

array([87, 83, 69, 80, 87, 71, 10, 10, 24, 72, 53, 39, 69, 88, 79])

In [3]:
np.sort(a)

array([10, 10, 24, 39, 53, 69, 69, 71, 72, 79, 80, 83, 87, 87, 88])

In [4]:
np.sort(b,axis=0)

array([[16,  5, 14,  7],
       [20, 20, 16, 23],
       [21, 68, 28, 41],
       [33, 71, 35, 42],
       [54, 74, 58, 78],
       [71, 92, 78, 97]])

In [5]:
np.sort(a)[::-1]

array([88, 87, 87, 83, 80, 79, 72, 71, 69, 69, 53, 39, 24, 10, 10])

In [6]:
a

array([87, 83, 69, 80, 87, 71, 10, 10, 24, 72, 53, 39, 69, 88, 79])

In [7]:
np.append(a,200)

array([ 87,  83,  69,  80,  87,  71,  10,  10,  24,  72,  53,  39,  69,
        88,  79, 200])

In [8]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[71., 68., 16., 41.,  1.],
       [21., 92., 58., 23.,  1.],
       [20., 20., 35., 78.,  1.],
       [16., 74., 28.,  7.,  1.],
       [33.,  5., 14., 97.,  1.],
       [54., 71., 78., 42.,  1.]])

In [9]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)


In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [11]:
e = np.array([1,2,3,4,3,2,1])
np.unique(e)

array([1, 2, 3, 4])

In [12]:
a

array([87, 83, 69, 80, 87, 71, 10, 10, 24, 72, 53, 39, 69, 88, 79])

In [13]:
np.expand_dims(a,axis=0)


array([[87, 83, 69, 80, 87, 71, 10, 10, 24, 72, 53, 39, 69, 88, 79]])

In [14]:
np.where(a>50)

(array([ 0,  1,  2,  3,  4,  5,  9, 10, 12, 13, 14], dtype=int64),)

In [15]:
np.where(a>50,0,a)

array([ 0,  0,  0,  0,  0,  0, 10, 10, 24,  0,  0, 39,  0,  0,  0])

In [16]:
np.where(a%2==0,0,a)

array([87, 83, 69,  0, 87, 71,  0,  0,  0,  0, 53, 39, 69,  0, 79])

In [17]:
np.argmax(a)

13

In [18]:
np.argmax(b,axis=0)

array([0, 1, 5, 4], dtype=int64)

In [19]:
np.argmin(a)

6

In [20]:
a

array([87, 83, 69, 80, 87, 71, 10, 10, 24, 72, 53, 39, 69, 88, 79])

In [21]:
np.cumsum(a)

array([ 87, 170, 239, 319, 406, 477, 487, 497, 521, 593, 646, 685, 754,
       842, 921])

In [22]:
np.cumsum(b,axis=1)

array([[ 71, 139, 155, 196],
       [ 21, 113, 171, 194],
       [ 20,  40,  75, 153],
       [ 16,  90, 118, 125],
       [ 33,  38,  52, 149],
       [ 54, 125, 203, 245]])

In [23]:
np.cumprod(a)

array([         87,        7221,      498249,    39859920,  -827154256,
        1401589968,  1130997792, -1574923968,   856530432,  1540648960,
          50016256,  1950633984,  1449758720, -1270251520, -1565622272])

In [24]:
np.percentile(a,100)

88.0

In [25]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 1, 1, 0, 1, 2, 3, 5, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [26]:
s = np.array([2000,4000,6000])
e =np.array([1,2,3])

np.corrcoef(s,e)

array([[1., 1.],
       [1., 1.]])

In [27]:
a

array([87, 83, 69, 80, 87, 71, 10, 10, 24, 72, 53, 39, 69, 88, 79])

In [28]:
items = [5,7,92]

In [29]:
a[np.isin(a,items)]

array([], dtype=int32)

In [30]:
np.flip(a)

array([79, 88, 69, 39, 53, 72, 24, 10, 10, 71, 87, 80, 69, 83, 87])

In [31]:
np.flip(b)

array([[42, 78, 71, 54],
       [97, 14,  5, 33],
       [ 7, 28, 74, 16],
       [78, 35, 20, 20],
       [23, 58, 92, 21],
       [41, 16, 68, 71]])

In [32]:
np.put(a,[0,1],[110,530])

In [33]:
a

array([110, 530,  69,  80,  87,  71,  10,  10,  24,  72,  53,  39,  69,
        88,  79])

In [34]:
np.delete(a,0)

array([530,  69,  80,  87,  71,  10,  10,  24,  72,  53,  39,  69,  88,
        79])

In [35]:
np.delete(a,[2,4])

array([110, 530,  80,  71,  10,  10,  24,  72,  53,  39,  69,  88,  79])

In [36]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,7,8])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 7, 8])

In [37]:
np.intersect1d(m,n)

array([3, 4, 5])

In [38]:
np.setdiff1d(m,n)

array([1, 2])

In [39]:
np.setxor1d(m,n)

array([1, 2, 7, 8])

In [41]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 69, 75, 75, 71, 25, 25, 25, 72, 53, 39, 69, 75, 75])